aws:
  region: us-east-1
  bucketName: BUCKET_NAME
  key: AWS_ACCESS_KEY_ID
  secret: AWS_SECRET_ACCESS_KEY
  sqs:
    queue-upload: https://sqs.us-east-1.amazonaws.com/438365882822/video-upload
    queue-update: https://sqs.us-east-1.amazonaws.com/438365882822/video-updated

